FROM registry.access.redhat.com/ubi9/ubi:9.6 AS builder
ARG TARGETARCH
ARG MINIO_RELEASE
ARG MC_VERSION=RELEASE.2025-08-13T08-35-41Z

ENV GOPATH=/go
ENV CGO_ENABLED=0

RUN dnf install -y --disablerepo=* --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms wget git make && dnf clean all

ARG GO_VERSION=1.24.9
RUN wget -q https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz -O go.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm go.tar.gz

# Add the Go binary directory to the system's PATH.
ENV PATH="/usr/local/go/bin:${PATH}"

# --- Build MinIO Server ---
WORKDIR /src/minio
# Clone the MinIO source code from GitHub.
RUN git clone --branch ${MINIO_RELEASE} --single-branch https://github.com/minio/minio.git .
# Build the MinIO binary. The output will be a single 'minio' executable.
RUN make

# --- Build MinIO Client (mc) ---
WORKDIR /src/mc
# Clone the MinIO Client (mc) source code from GitHub.
RUN git clone --branch ${MC_VERSION} --single-branch https://github.com/minio/mc.git .
# Build the mc binary. The output will be a single 'mc' executable.
RUN make

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

ENV MINIO_ACCESS_KEY_FILE=access_key \
    MINIO_SECRET_KEY_FILE=secret_key \
    MINIO_ROOT_USER_FILE=access_key \
    MINIO_ROOT_PASSWORD_FILE=secret_key \
    MINIO_KMS_SECRET_KEY_FILE=kms_master_key \
    MINIO_CONFIG_ENV_FILE=config.env \
    MC_CONFIG_DIR=/tmp/.mc

COPY --from=builder /src/minio/minio /usr/bin/
COPY --from=builder /src/mc /usr/bin/

EXPOSE 9000
VOLUME ["/data"]

# TODO: Run as non-root user

ENTRYPOINT ["minio"]
